# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - automated-ringcentral-irslogics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for requesting the JWT
      contents: read  # required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (for optional tests only)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # (Optional) Run tests before deploy
      # - name: Install dependencies for tests
      #   run: pip install -r requirements.txt
      # - name: Run tests
      #   run: pytest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C7BB3F0429AC405386EB9EBDD13BAF5B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4A82414C3834289831D34A30842945F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_72136D5926B3459EB8721647AF9D6025 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'automated-ringcentral-irslogics'
          slot-name: 'Production'
          package: .
